spring:
  application:
    name: springboot-kafka-producer
  profiles:
    active: local
eureka:
  client:
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://naming-server:8761/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME:localhost}:${MYSQL_PORT:3306}/test?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:3113327}
  kafka:
    template:
      default-topic: log-inout-events
    producer:
      bootstrap-servers: ${KAFKA_BROKER_HOSTNAME:localhost}:${KAFKA_BROKER_PORT:9092}
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: ${KAFKA_BROKER_HOSTNAME:localhost}:${KAFKA_BROKER_PORT:9092}
---
spring:
  profiles: nonprod
  kafka:
    template:
      default-topic: log-inout-events
    producer:
      bootstrap-servers: localhost:9091,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/D:/MyMind/personel/Improvments/Sample Apps/Apache Kafka/dev/ssl/client.truststore.jks
        trust-store-password: 3113327
        key-store-location: file:/D:/MyMind/personel/Improvments/Sample Apps/Apache Kafka/dev/ssl/client.keystore.jks
        key-store-password: 3113327
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:

---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
        transaction:
          interceptor: TRACE
